artifact_location: file:///C:/Users/mhbk8/OneDrive/Desktop/Olist%20Project/mlruns/0
creation_time: 1729895290990
experiment_id: '0'
last_update_time: 1729895290990
lifecycle_stage: active
name: Default
